spring:
  application:
    name: db-comparison

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        # 🔥 batching
        jdbc.batch_size: 300
        order_inserts: false
        order_updates: true
        jdbc.batch_versioned_data: true
        # szybkie fetchy przy odczycie
        default_batch_fetch_size: 500
        jdbc.fetch_size: 500
        # wyłącz statystyki hibernate, bo spowalniają przy dużych insertach
        generate_statistics: true
        connection.provider_disables_autocommit: false

server:
  shutdown: graceful

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

benchmark:
  recordCount: 10000
  threads: 32
  batchSize: 1000
  warmupPercent: 1
  isolation: "READ_COMMITTED"

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: >
      jdbc:mysql://localhost:3306/db_comparison
      ?useSSL=false&allowPublicKeyRetrieval=true
      &rewriteBatchedStatements=true
      &cachePrepStmts=true
      &useServerPrepStmts=false
      &prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
      &useLocalTransactionState=true
      &useLocalSessionState=true
      &cacheServerConfiguration=true
      &elideSetAutoCommits=false
      &useUnicode=true&characterEncoding=UTF-8
      &connectionCollation=utf8mb4_unicode_ci&characterSetResults=utf8mb4
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 16
      minimum-idle: 8
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepaliveTime: 300000
      auto-commit: false
  jpa:
    properties:
      hibernate.dialect.storage_engine: innodb
    database-platform: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/db_comparison?reWriteBatchedInserts=true&sslmode=disable&tcpKeepAlive=true&socketTimeout=0&options=-c%20statement_timeout=0
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 16
      minimum-idle: 8
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepaliveTime: 300000
      auto-commit: false
      data-source-properties:
        socketTimeout: 60
        tcpKeepAlive: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
