apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true

  - name: MySQL
    type: mysql
    url: mysql:3306
    database: db_comparison
    user: root
    secureJsonData:
      password: root
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: db_comparison
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
